---
abstract: 'Perl Moose Roles and methods for the Genome Analysis Toolkit (i.e. GATK)'
author:
  - 'Richard de Borja <richard.deborja@sickkids.ca>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.143240'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: NGS-Tools-GATK
provides:
  NGS::Tools::GATK:
    file: lib/NGS/Tools/GATK.pm
    version: '0.12'
  NGS::Tools::GATK::Roles::BaseRecalibrator:
    file: lib/NGS/Tools/GATK/Roles/BaseRecalibrator.pm
  NGS::Tools::GATK::Roles::CombineVariants:
    file: lib/NGS/Tools/GATK/Roles/CombineVariants.pm
  NGS::Tools::GATK::Roles::Core:
    file: lib/NGS/Tools/GATK/Roles/Core.pm
  NGS::Tools::GATK::Roles::DepthOfCoverage:
    file: lib/NGS/Tools/GATK/Roles/DepthOfCoverage.pm
  NGS::Tools::GATK::Roles::HaplotypeCaller:
    file: lib/NGS/Tools/GATK/Roles/HaplotypeCaller.pm
  NGS::Tools::GATK::Roles::IndelRealigner:
    file: lib/NGS/Tools/GATK/Roles/IndelRealigner.pm
  NGS::Tools::GATK::Roles::MuTect2:
    file: lib/NGS/Tools/GATK/Roles/MuTect2.pm
  NGS::Tools::GATK::Roles::Pileup:
    file: lib/NGS/Tools/GATK/Roles/Pileup.pm
  NGS::Tools::GATK::Roles::PrintReads:
    file: lib/NGS/Tools/GATK/Roles/PrintReads.pm
  NGS::Tools::GATK::Roles::RealignerTargetCreator:
    file: lib/NGS/Tools/GATK/Roles/RealignerTargetCreator.pm
  NGS::Tools::GATK::Roles::UnifiedGenotyper:
    file: lib/NGS/Tools/GATK/Roles/UnifiedGenotyper.pm
requires:
  Carp: '0'
  File::Basename: '0'
  File::Find::Rule: '0.3'
  Moose: '0'
  Moose::Role: '0'
  MooseX::Params::Validate: '0'
version: '0.12'
